version: "3"
services:
  container_todo_mysql:
    image: taitaicomedy/todo_mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: wangtianyi
      MYSQL_PASSWORD: 123456

  container_todo_app:
    image: taitaicomedy/todo_app
    ports:
      - "8080:8888"
    depends_on:
      - container_todo_mysql