version: "3"
services:
  container_todo_mysql:
    image: taitaicomedy/todo_mysql:1.0 # MySQL数据库镜像，含todo表和wangtianyi用户
    ports:
      - "13306:3306" # 如果执行后提示13306端口被占用或其他原因，左边那个13306端口也可以改成其它未被占用的端口，右边那个3306不要修改。
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: wangtianyi # MySQL用户和密码维持这样就可以，不需要修改，不会干扰宿主机的数据库。
      MYSQL_PASSWORD: 123456

  container_todo_app:
    image: taitaicomedy/todo_app:1.0 # 后端程序镜像
    ports:
      - "8234:8234" # 如果执行后提示8234端口被占用或其他原因，左边那个8234端口也可以改成其它未被占用的端口，但是一定要去/myprojects/todolist/todo_frontend/src/main,js里把端口号改成与此处一致，并且重新npm run build和cp dist。右边那个8234不要修改。
    depends_on:
      - container_todo_mysql

  container_todo_nginx:
    image: nginx:1.23.2  # nginx http服务器镜像，用于部署vue
    ports:
      - "8112:80" # 如果执行后提示8111端口被占用或其他原因，左边那个8111端口也可以改成其它未被占用的端口，这里是几，在浏览器地址栏输入的端口就是几。右边那个80是nginx的监听端口，不要修改。
    volumes:
      - /myprojects/todolist/todo_nginx_conf/html:/usr/share/nginx/html
      - /myprojects/todolist/todo_nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - /myprojects/todolist/todo_nginx_conf/logs:/var/log/nginx
      - /myprojects/todolist/todo_nginx_conf/conf:/etc/nginx/conf.d
